### PR TITLE
Fix shard parsing and update dependencies

### LINKED ISSUE #9: (large bot sharding) shard ID in URL does not work
as mentioned in the support server, `&request.uri().to_string()` only outputs `/?shard=42` instead of a full path so Url::parse isn't able to parse it

### PR DESCRIPTION
**Pull request by Gelbpunkt**
This uses `serde_urlencoded` for parsing the shard ID from the query parameters and updates the dependencies to use twilight 0.8.

Fixes #9

### CODE REVIEW

**Comment by 7596ff** [comment]
Can we add a test?

**Comment by Gelbpunkt** [comment]
> Can we add a test?

Since we're relying on an external crate here, I don't think testing makes sense. They have their own tests and we should assure that we're calling it properly.

**Comment by 7596ff** [comment]
I think it would be good if the bug that we're fixing is clearly shown to be fixed, even if reading the code also portrays that. But if you don't think so then just request my review.

**Review by 7596ff — APPROVED** [review]

File: src/main.rs [hunk 1]
```diff
@@ -73,9 +78,7 @@ async fn main() -> Result<(), Box<dyn Error>> {
 
             big_queue = concurrency > 1;
 
-            Arc::new(Box::new(
-                LargeBotQueue::new(concurrency, &http_client).await,
-            ))
+            Arc::new(Box::new(LargeBotQueue::new(concurrency, http_client).await))
```
Comment (vilgotf) [inline src/main.rs]: FYI: Boxing inside of an Arc is totally unnecessary
